# Generated by Django 4.1.3 on 2022-12-27 20:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_de_profil',
            field=models.ImageField(upload_to='', verbose_name='Photo de profil'),
        ),
    ]
